#!/bin/bash
# One environment for task validation and teacher generation.
# ./setup.sh /path/to/workspace [--cluster helma] [--python /path/to/python3.12]
set -euo pipefail
here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ws=${1:?Usage: setup.sh /path/to/workspace [--cluster NAME] [--python PATH]}
shift
cluster=
python_override=
while (( $# )); do
    case "$1" in
        --cluster) cluster=${2:?}; shift 2 ;;
        --python) python_override=${2:?}; shift 2 ;;
        *) echo "Unknown argument: $1" >&2; exit 2 ;;
    esac
done
if [[ -z "$cluster" ]]; then
    cluster=$(python3 - "$here" <<'DETECT'
import sys
sys.path.insert(0, sys.argv[1])
from config.clusters import detect_cluster
cluster = detect_cluster()
if cluster is None:
    raise SystemExit('Unknown cluster; pass --cluster NAME')
print(cluster.name)
DETECT
    )
fi
# Bootstrap uses only the standard library; it does not install into system Python.
runtime_exports=$(python3 "$here/config/runtime.py" shell --cluster "$cluster")
eval "$runtime_exports"
if [[ -n "$OT_PYTHON_MODULE" ]]; then module load "$OT_PYTHON_MODULE"; fi
if [[ -n "$OT_APPTAINER_MODULE" ]]; then module load "$OT_APPTAINER_MODULE"; fi
if [[ -n "$OT_CUDA_MODULE" ]]; then module load "$OT_CUDA_MODULE"; fi
python_bin=${python_override:-$OT_PYTHON_EXECUTABLE}
command -v "$python_bin" >/dev/null || {
    echo "Python executable $python_bin not found. Pass --python /path/to/python3.12 or configure python_module in config/clusters.py." >&2
    exit 1
}
"$python_bin" "$here/config/runtime.py" check --cluster "$cluster" --system-only
mkdir -p "$ws"
ws=$(cd "$ws" && pwd)
# Keep one explicit source environment; compute jobs use its local staged copy.
prep_env=${OT_PREP_ENV:-${OT_DEFAULT_PREP_ENV:-$ws/envs/prep}}
mkdir -p "$prep_env"
prep_env=$(cd "$prep_env" && pwd)
if [[ -x "$prep_env/bin/python" ]]; then
    "$prep_env/bin/python" "$here/config/runtime.py" check --cluster "$cluster" --system-only
else
    "$python_bin" -m venv "$prep_env"
fi
"$prep_env/bin/python" -m ensurepip --upgrade
"$prep_env/bin/python" -m pip install -r "$here/requirements.txt"
"$prep_env/bin/python" -m pip check
"$prep_env/bin/python" "$here/config/runtime.py" check --cluster "$cluster"
"$prep_env/bin/python" -m pip freeze > "$prep_env/requirements-resolved.txt"
# Shell-quote generated paths, including spaces. Source the standard activation.
{
    printf '%s\n' '# Generated by setup.sh. Source in each new shell.'
    printf 'export OT_WORKSPACE=%q\n' "$ws"
    printf 'export OT_NEXT_DATA=%q\n' "$here"
    printf 'export OT_CLUSTER=%q\n' "$cluster"
    printf 'export OT_PREP_ENV=%q\n' "$prep_env"
    printf 'export OT_RUNTIME_BUNDLE=%q\n' "$ws/runtime/prep.json"
    if [[ -n "$OT_APPTAINER_MODULE" ]]; then printf 'module load %q\n' "$OT_APPTAINER_MODULE"; fi
    if [[ -n "$OT_PYTHON_MODULE" ]]; then printf 'module load %q\n' "$OT_PYTHON_MODULE"; fi
    printf 'source %q\n' "$prep_env/bin/activate"
    printf 'eval "$(%q %q storage --cluster %q)"\n' "$prep_env/bin/python" "$here/config/runtime.py" "$cluster"
    printf 'export PYTHONPATH=%q${PYTHONPATH:+:$PYTHONPATH}\n' "$here"
    if [[ -n "$OT_CUDA_MODULE" ]]; then printf 'module load %q\n' "$OT_CUDA_MODULE"; fi
} > "$here/env.sh"
# Jobs stage a copy of this same environment on node-local disk.
# This is a transport archive, not a second set of dependencies or a GPU image.
"$prep_env/bin/python" "$here/hpc/local_runtime.py" build \
    "$prep_env" "$ws/runtime/prep.tar"
echo "Ready: source $here/env.sh"
echo "Next: python -m validation.upstream setup"
echo "Download model weights with: python config/models.py --download MODEL"
