"""Build a self-contained host runtime and stage it before starting validation.

The bundle is built on the login node after environment updates. No Python code
from the shared environment is imported by the compute-node bootstrap.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import shlex
import shutil
import subprocess
import tarfile
import tempfile


def digest(path):
    value = hashlib.sha256()
    with Path(path).open('rb') as stream:
        for chunk in iter(lambda: stream.read(8 * 1024 * 1024), b''):
            value.update(chunk)
    return value.hexdigest()


def relocate(root, metadata):
    env, base = root / 'env', root / 'python'
    interpreter = base / 'bin' / metadata['executable']
    for path in (env / 'bin').iterdir():
        if path.name in ('python', 'python3', metadata['executable']):
            path.unlink(missing_ok=True)
            path.symlink_to(interpreter)
        elif path.is_file() and not path.is_symlink():
            data = path.read_bytes()
            if data.startswith(b'#!') and b'python' in data.split(b'\n', 1)[0]:
                path.write_bytes(b'#!' + str(env / 'bin/python').encode() + b'\n' + data.split(b'\n', 1)[1])
    (env / 'pyvenv.cfg').write_text('home = ' + str(base / 'bin') + '\ninclude-system-site-packages = false\n')
    # Reject editable installs/path injections instead of quietly reading home.
    for pth in env.glob('lib/python*/site-packages/*.pth'):
        for line in pth.read_text().splitlines():
            if line.strip() and not line.startswith(('#', 'import ')):
                target = (pth.parent / line.strip()).resolve()
                if not target.is_relative_to(root):
                    raise ValueError(f'Nonlocal package path in {pth}: {line}')
    for link in root.rglob('*'):
        if link.is_symlink() and not link.resolve().is_relative_to(root):
            raise ValueError(f'Runtime symlink escapes local staging: {link}')


def build(environment, output):
    environment = environment.resolve()
    info = json.loads(subprocess.check_output([str(environment / 'bin/python'), '-I', '-c',
        'import sys,json; from pathlib import Path; print(json.dumps({"base":sys.base_prefix,"executable":Path(sys.executable).resolve().name}))'], text=True))
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix='runtime-build-') as temporary:
        root = Path(temporary)
        shutil.copytree(info['base'], root / 'python', symlinks=False)
        shutil.copytree(environment, root / 'env', symlinks=False)
        info['environment'] = str(environment)
        (root / 'runtime.json').write_text(json.dumps(info, indent=2))
        relocate(root, info)
        # Use relative links in the archive; stage() rewrites executable paths.
        for name in ('python', 'python3', info['executable']):
            link = root / 'env/bin' / name
            link.unlink(missing_ok=True)
            link.symlink_to('../../python/bin/' + info['executable'])
        archive = root / 'bundle.tar'
        with tarfile.open(archive, 'w') as tar:
            for name in ('python', 'env', 'runtime.json'):
                tar.add(root / name, arcname=name)
        checksum = digest(archive)
        # Content-addressed bundles are immutable, including while jobs read them.
        target = output.parent / (output.stem + '-' + checksum + '.tar')
        pending_archive = target.with_suffix(".tmp")
        shutil.copyfile(archive, pending_archive)
        pending_archive.replace(target)
        pointer = output.with_suffix('.json')
        pending = pointer.with_suffix('.tmp')
        pending.write_text(json.dumps({'archive': str(target), 'sha256': checksum, **info}, indent=2))
        pending.replace(pointer)
        print(pointer)


def stage(bundle, source, root):
    root = root.resolve()
    root.mkdir(parents=True)  # Never reuse a partially staged runtime.
    manifest = json.loads(bundle.read_text())
    archive = root / 'runtime.tar'
    shutil.copyfile(manifest['archive'], archive)
    if digest(archive) != manifest['sha256']:
        raise ValueError('Runtime bundle checksum mismatch')
    with tarfile.open(archive) as tar:
        # Bundle is generated by build(); still reject escaping member paths.
        for member in tar.getmembers():
            if not (root / member.name).resolve().is_relative_to(root):
                raise ValueError('Runtime archive path escapes staging')
            if member.issym() and not (root / member.name).parent.joinpath(member.linkname).resolve().is_relative_to(root):
                raise ValueError('Runtime archive symlink escapes staging')
            if member.islnk() or member.isdev():
                raise ValueError('Unsupported runtime archive member')
        tar.extractall(root)
    archive.unlink()
    relocate(root, manifest)
    code = root / 'code'
    code.mkdir()
    for name in ('validation', 'config', 'harbor_patches', 'hpc', 'data/annotate_dataset', 'data/utils', 'data/seta'):
        if (source / name).exists():
            shutil.copytree(source / name, code / name, symlinks=False,
                ignore=shutil.ignore_patterns('__pycache__', '*.pyc', 'results', 'runs', 'submissions'))
    shutil.copyfile(source / 'requirements.txt', code / 'requirements.txt')
    if (source / 'data/__init__.py').is_file():
        shutil.copyfile(source / 'data/__init__.py', code / 'data/__init__.py')
    # Frozen submission snapshots currently link external/ back to the checkout.
    # Dereference it once before any service starts; include Git metadata for pins.
    pins = json.loads((code / 'validation/upstream/upstream.lock.json').read_text())
    for name in pins:
        shutil.copytree(source / 'external' / name, code / 'external' / name, symlinks=False)
    values = {'VALIDATION_REPO': str(code), 'OT_NEXT_DATA': str(code),
        'HARBOR_BRIDGE_VENV': str(root / 'env'), 'VIRTUAL_ENV': str(root / 'env'),
        'PYTHONPATH': str(code), 'PYTHONNOUSERSITE': '1',
        'PATH': str(root / 'env/bin') + ':' + os.environ['PATH'],
        'OT_LOCAL_RUNTIME': str(root)}
    for variable, suffix in {'XDG_CACHE_HOME': 'cache', 'HF_HOME': 'cache/huggingface',
        'APPTAINER_CACHEDIR': 'cache/apptainer', 'UV_CACHE_DIR': 'cache/uv',
        'PIP_CACHE_DIR': 'cache/pip', 'VLLM_CACHE_ROOT': 'cache/vllm',
        'TRITON_CACHE_DIR': 'cache/triton', 'TORCH_HOME': 'cache/torch',
        'CUDA_CACHE_PATH': 'cache/cuda', 'FLASHINFER_WORKSPACE_BASE': 'cache/flashinfer'}.items():
        values[variable] = str(root / suffix)
        (root / suffix).mkdir(parents=True, exist_ok=True)
    (root / 'env.sh').write_text('unset PYTHONHOME\n' + ''.join(
        'export ' + key + '=' + shlex.quote(value) + '\n' for key, value in values.items()))
    (root / 'staging.json').write_text(json.dumps({'bundle': manifest, 'code_source': str(source),
        'local_root': str(root)}, indent=2))
    print('Host runtime staged at ' + str(root), flush=True)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest='action', required=True)
    command = sub.add_parser('build')
    command.add_argument('environment', type=Path)
    command.add_argument('output', type=Path)
    command = sub.add_parser('stage')
    command.add_argument('bundle', type=Path)
    command.add_argument('source', type=Path)
    command.add_argument('root', type=Path)
    args = parser.parse_args()
    if args.action == 'build':
        build(args.environment, args.output)
    else:
        stage(args.bundle, args.source, args.root)
