"""Write task-provenance.csv: for every one of the 9,659 original tasks, whether it is in the
output and at which stage and for which reason it was left out (python with pyarrow).

  python provenance.py [--max-verify-seconds 300]

Stages, in the order the patch script applies them:
  1 build-recipe    a verified build recipe exists (all 9,659 tasks; none is dropped here)
  2 warning-audit   the analyzer reproduces the warning on the buggy file and the historical fix
                    removes it (DISCARDED_TASKS, generated by the audit and its recovery)
  3 verifier-run    the packaged verifier itself, on the buggy file (verifier_accepts_buggy_file)
  4 verification-time  measured build plus analysis within --max-verify-seconds
"""
import argparse
import csv
import importlib.util
from pathlib import Path
import sys
from types import SimpleNamespace

here = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location('inferredbugs_patcher', here.parent / 'patch_tasktrove_inferredbugs_v3.py')
patcher = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = patcher
spec.loader.exec_module(patcher)

REASONS = {
    'reference_retains_warning': ('warning-audit', 'Infer still reports the warning after the historical fix, so the fix is not a solution'),
    'reference_same_warning_key': ('warning-audit', 'after the historical fix Infer reports a warning with the same key, so a fixed file could not be told from the buggy one'),
    'buggy_never_compiles': ('warning-audit', 'the buggy file does not compile in any version of the project'),
    'warning_not_reproduced': ('warning-audit', 'Infer does not report the warning on the buggy file, with any of its releases'),
    'reference_not_analyzed': ('warning-audit', 'Infer reports the warning on the buggy file, but the project after the fix could not be analyzed'),
    'build_or_analysis_failure': ('warning-audit', 'the project with the buggy file could not be built or analyzed'),
    'verifier_accepts_buggy_file': ('verifier-run', 'the packaged verifier gave the buggy file reward 1: Infer did not report the warning in that run'),
}


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--max-verify-seconds', type=int, default=300)
    ap.add_argument('--output', default=str(here.parent / 'task-provenance.csv'))
    a = ap.parse_args()
    rows = []
    for r in patcher.embedded_recipes():
        task = r['task_id']
        times = patcher.verification_times(task)
        if task in patcher.DISCARDED:
            stage, reason = REASONS[patcher.DISCARDED[task]]
            kept = 'no'
        elif a.max_verify_seconds and times and times['build'] + times['analyze'] > a.max_verify_seconds:
            stage, reason, kept = 'verification-time', 'building and analyzing the project takes more than %d seconds' % a.max_verify_seconds, 'no'
        else:
            stage, reason, kept = '', '', 'yes'
        rows.append({'task_id': task, 'language': r['language'], 'project': r['project'], 'kept': kept, 'dropped_at': stage,
                     'reason': reason, 'analyzer': patcher.task_analyzer(SimpleNamespace(task_id=task, language=r['language'])),
                     'build_seconds': times['build'] if times else '', 'analysis_seconds': times['analyze'] if times else ''})
    rows.sort(key=lambda r: r['task_id'])
    with open(a.output, 'w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0]))
        w.writeheader()
        w.writerows(rows)
    import collections
    print(len(rows), 'tasks;', sum(r['kept'] == 'yes' for r in rows), 'kept')
    for (stage, reason), n in sorted(collections.Counter((r['dropped_at'], r['reason']) for r in rows if r['kept'] == 'no').items()):
        print('%5d  %-18s %s' % (n, stage, reason))


if __name__ == '__main__':
    main()
